/**
 * TypeScript types for Supabase
 * 
 * These types are automatically generated by Supabase.
 * Run this command to generate types from your database:
 * 
 * npx supabase gen types typescript --project-id your-project-id > types/supabase.ts
 * 
 * Or use the Supabase CLI:
 * supabase gen types typescript --local > types/supabase.ts
 */

// Placeholder types - will be generated from your Supabase project
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
      }
    }
    Views: {
      [key: string]: {
        Row: Record<string, unknown>
      }
    }
    Functions: {
      [key: string]: {
        Args: Record<string, unknown>
        Returns: unknown
      }
    }
  }
}

